# Generated by Django 5.2.6 on 2025-09-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_subjectiveanswer_graded'),
        ('users', '0002_user_address_user_age_user_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
        ),
    ]
