# Generated by Django 5.2.6 on 2025-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
