# Generated by Django 5.2.6 on 2025-09-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
