# Generated by Django 5.2.6 on 2025-09-21 18:46

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_retakerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='action',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('download', 'Download'), ('retake_request', 'Retake Request'), ('grade', 'Grade'), ('review', 'Review'), ('notification', 'Notification')], default=datetime.timedelta(0), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='description',
            field=models.TextField(default=datetime.datetime(2025, 9, 21, 18, 45, 56, 683278, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
