# Generated by Django 5.2.6 on 2025-10-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentquizattempt_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizattempt',
            name='total_score',
        ),
    ]
