# Generated by Django 5.2.6 on 2025-09-13 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquizattempt',
            old_name='is_submitted',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='studentquizattempt',
            old_name='completed_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='studentquizattempt',
            old_name='total_marks',
            new_name='retake_count',
        ),
        migrations.RemoveField(
            model_name='studentquizattempt',
            name='score',
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='retake_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.quiz'),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
