# Generated by Django 5.2.6 on 2025-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_actionlog_action_actionlog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('download', 'Download'), ('retake_request', 'Retake Request'), ('grade', 'Grade'), ('review', 'Review'), ('notification', 'Notification'), ('pended', 'Pended'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
