# Generated by Django 5.2.6 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_is_submitted_studentquizattempt_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
