# Generated by Django 5.2.6 on 2025-10-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_studentquizattempt_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
