# Generated by Django 5.2.6 on 2025-09-24 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_actionlog_action_type_alter_answer_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
