# Generated by Django 5.2.6 on 2025-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentquizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectiveanswer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
