# Generated by Django 5.2.6 on 2025-09-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_subjectiveanswer_graded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectiveanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='subjectiveanswer',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='subjectiveanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ObjectiveAnswer',
        ),
        migrations.DeleteModel(
            name='SubjectiveAnswer',
        ),
    ]
