# Generated by Django 5.2.6 on 2025-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studentquizattempt_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='retake_requested',
            field=models.BooleanField(default=False),
        ),
    ]
