# Generated by Django 5.2.6 on 2025-09-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_quiz_class_level_quiz_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='class_level',
            new_name='school_class',
        ),
    ]
