# Generated by Django 5.2.6 on 2025-09-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_rename_class_level_quiz_school_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquizattempt',
            old_name='completed',
            new_name='is_submitted',
        ),
        migrations.RenameField(
            model_name='studentquizattempt',
            old_name='completed_at',
            new_name='submitted_at',
        ),
    ]
