# Generated by Django 5.2.6 on 2025-10-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_rename_completed_studentquizattempt_is_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='obtained_marks',
            new_name='score',
        ),
    ]
