# Generated by Django 5.2.6 on 2025-10-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_rename_obtained_marks_answer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='score',
            new_name='obtained_marks',
        ),
    ]
