# Generated by Django 5.2.6 on 2025-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_rename_score_answer_obtained_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='is_retake_approved',
            field=models.BooleanField(default=False),
        ),
    ]
