# Generated by Django 5.2.6 on 2025-10-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_studentquizattempt_is_retake_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='obtained_marks',
            new_name='score',
        ),
    ]
