# Generated by Django 5.2.6 on 2025-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_rename_obtained_marks_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
