# Generated by Django 5.2.6 on 2025-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_studentquizattempt_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='graded_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-7'),
            preserve_default=False,
        ),
    ]
