# Generated by Django 5.2.6 on 2025-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_answer_graded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
